version: '3.4'

services:
  manager:
    image: emqx/edge-manager:1.1.1
    container_name: edge-manager
    ports:
      - "9082:9082"
  kuiper:
    image: emqx/kuiper:1.2.0-slim
    ports:
      - "9081:9081"
      - "20498:20498"
    container_name: manager-kuiper
    hostname: manager-kuiper
    environment:
      MQTT_SOURCE__DEFAULT__SERVERS: "[tcp://manager-edge:1883]"
  edge:
    image: emqx/emqx-edge:latest
    ports:
      - "8081:8081"
      - "1883:1883"
      - "18083:18083"
    container_name: manager-edge
    hostname: manager-edge
  taos:
    image: tdengine/tdengine:2.0.3.1
    ports:
      - "6030:6030"
      - "6035:6035"
      - "6041:6041"
      - "6030-6040:6030-6040/udp"
    container_name: manager-taos
    hostname: taos
    volumes:
      - taos-grafana-plugin:/root/TDengine-server/connector/grafanaplugin
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: manager-grafana
    hostname: manager-grafana
    volumes:
      - taos-grafana-plugin:/var/lib/grafana/plugins/taosplugin
    depends_on:
      - taos

volumes:
  taos-grafana-plugin:
