version: '3.4'

services:
  security-bootstrapper:
    image: sim:1
    container_name: manager-security
    hostname: manager-security
    volumes:
      - init-passwd:/go/sim/etc:z
  kuiper:
    image: emqx/kuiper:1.1.2-alpine
    ports:
      - "127.0.0.1:9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: manager-kuiper
    hostname: manager-kuiper
    depends_on:
      - security-bootstrapper
    environment:
      EDGEX__DEFAULT__PORT: 5566
      EDGEX__DEFAULT__PROTOCOL: tcp
      EDGEX__DEFAULT__SERVER: edgex-app-service-configurable-rules
      EDGEX__DEFAULT__SERVICESERVER: http://edgex-core-data:48080
      EDGEX__DEFAULT__TOPIC: events
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: 48075
    volumes:
      - init-passwd:/kuiper/etc/sources:z

volumes:
  init-passwd: